# Copyright (c) 2023-2026 UChicago Argonne, LLC
# SPDX-License-Identifier: LicenseRef-UChicago-Argonne-LLC-License
"""Package-level initialization."""

import importlib.metadata

__settings_orgName__ = "bluesky"
"""GitHub organization/user name"""

__package_name__ = "hklpy2"
"""GitHub repository name and Python package name."""


def _get_version(version_module=None):
    """
    Return package version.

    Priority:

    1. From ``_version.py`` (generated by ``setuptools_scm``) if exists.
    2. Try ``importlib.metadata.version()``.
    3. Fall back to a safe default.
    """
    # 1) try generated version file (recommended)
    if version_module is not None:
        ver = getattr(version_module, "version", None)
        if ver:
            return ver

    # 2) try importlib.metadata
    try:
        return importlib.metadata.version(__package_name__)
    except importlib.metadata.PackageNotFoundError:
        return "0+unknown"


__version__ = _get_version()  # Must define before these imports.
"""Package version string."""

if __name__ == "__main__":
    import sys

    print(f"Package version: {__version__}")
    sys.exit()

from .backends import SolverBase  # noqa: F401
from .blocks.configure import Configuration  # noqa: F401
from .blocks.lattice import SI_LATTICE_PARAMETER  # noqa: F401
from .blocks.zone import OrthonormalZone  # noqa: F401
from .diffract import creator  # noqa: F401
from .diffract import diffractometer_class_factory  # noqa: F401
from .exceptions import SolverError  # noqa: F401
from .incident import A_KEV  # noqa: F401
from .plans import move_zone  # noqa: F401
from .plans import scan_psi  # noqa: F401
from .plans import scan_zone  # noqa: F401
from .run_utils import ConfigurationRunWrapper  # noqa: F401
from .run_utils import get_run_orientation  # noqa: F401
from .run_utils import list_orientation_runs  # noqa: F401
from .run_utils import register_aux_reconstructor  # noqa: F401
from .run_utils import simulator_from_config  # noqa: F401
from .solver_utils import SOLVER_ENTRYPOINT_GROUP  # noqa: F401
from .solver_utils import get_solver  # noqa: F401
from .solver_utils import solver_factory  # noqa: F401
from .solver_utils import solvers  # noqa: F401
